// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
const connectionUrl = process.env.DATABASE_URL;

if (!connectionUrl) {
  throw new Error(
    "Не знойдзена зменная асяроддзя DATABASE_URL. Праверце .env файл."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Гэта імя павінна супадаць з імем у schema.prisma (datasource db)
    // url: connectionUrl,
    url: env("DATABASE_URL"),
  },

  // datasource: {
  //   url: env("DATABASE_URL"),
  // },
});
